### PR TITLE
some fixes to namedexpressions

### LINKED ISSUE #319: Use Named Expressions with `buildFromArray` and `buildFromSheets` factories
### Description

Currently, the engine has to be initialized with `buildEmpty`, then Named Expressions added with API methods, and finally we can `addSheet` / `setSheetContent`.

A new config option `namedExpressions: { expressionName: string, expression: RawCellContent, scope: number, ... otherOptions }` could help. Where `scope` is the sheetId and global if missing). Depends how we're going to implement it in #240 

```ts
HyperFormula.buildFromArray([ [ ... ] ], {
  namedExpressions: [
     { expressionName: 'TRUE', expression: '=TRUE()', visible: false }
  ]
})
```

### LINKED ISSUE #335: Get all Named Expressions method needed
### Description

I've noticed that we don't have a method to get all Named Expressions. It should be roughly the same format that #319 will accept. For example `getAllNamedExpressionsSerialized`

### Use case

We can get all sheets serialized with `getAllSheetsSerialized` send them to server and load the next day. But if sheets contain Named Expressions, they will not calculate correctly anymore. There should be a method that can get all Named Expressions serialized so we can store both in the database and recreate the engine in another browser session.

```ts
const sheetsData = engine.getAllSheetsSerialized()
const namedExpressionsData = engine.getAllNamedExpressionsSerialized()

const newEngine = HyperFormula.buildFromSheets(sheetsData, {
  namedExpressions: namedExpressionsData
})
```

### PR DESCRIPTION
**Pull request by izulin**
### Context

Fixes #335.
Fixes #319.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or improvement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Additional language file or change to the existing one (translations)

### Related issue(s):
1.
2.
3.

### Checklist:

- [x] My code follows the code style of this project,
- [ ] My change requires a change to the documentation,
- [x] I described the modification in the CHANGELOG.md file.

### CODE REVIEW

File: src/HyperFormula.ts [hunk 1]
```diff
@@ -293,8 +293,8 @@ export class HyperFormula implements TypedEmitter {
    *
    * @category Factories
    */
-  public static buildEmpty(configInput?: Partial<ConfigParams>): HyperFormula {
-    return this.buildFromEngineState(BuildEngineFactory.buildEmpty(configInput))
+  public static buildEmpty(configInput: Partial<ConfigParams> = {}, namedExpressions: SerializedNamedExpression[] = []): HyperFormula {
```
Comment (wojciechczerniak) [inline src/HyperFormula.ts:296]: Is it a good choice for `namedExpressions`? I think that by similarity to `functionPlugins` the should be placed within Config object.

On the other hand, Config is not a user content. It may be stored separately and be a constant. Sometimes hardcoded into the app. When we look at it like that, it makes sense to separate those contexts.

@izulin You probably thought that through already, WDYT?

**Review by wojciechczerniak — CHANGES_REQUESTED** [review]

File: src/HyperFormula.ts (hunk 1 above)
Comment (izulin) [reply src/HyperFormula.ts:296]: I think it should go other way around: If there was a way to hardcode it into the actual data (like in `buildFromArray` or `buildFromSheets`), it should be. But I cannot think of a way to make it so consistently without making unnecessary layers of complexity, so I think keeping it as a separate argument should do fine.

Comment (wojciechczerniak) [reply src/HyperFormula.ts:296]: Yup. And having it in Config will complicate updateConfig logic. Good choice

**Review by wojciechczerniak — APPROVED** [review]
