### PR TITLE
Fix: ADDRESS function ignores defaultValue when user provides empty value for an optional parameter

### LINKED ISSUE #1632: [Bug]: ADDRESS function ignores `defaultValue` when user provides empty value for an optional parameter
### Description

When a user passes an empty argument to `ADDRESS` (e.g. `=ADDRESS(1,1,)` or `=ADDRESS(1,1,1,)`), the `absNum` and `a1Style` parameters should use their declared `defaultValue` (1 and `true` respectively). Instead, `EmptyValue` is coerced to `0`/`false`, producing incorrect results.

**Note:** This applies **only to ADDRESS**. Excel 2021 and Google Sheets consistently treat empty arguments as the zero-value for the type (`0` for numbers, `FALSE` for booleans) across all other functions — that is correct behavior, not a bug. ADDRESS is the confirmed exception.

| Function | Parameter | empty arg (Excel) | omitted (Excel) | HF bug? |
|----------|-----------|-------------------|-----------------|---------|
| `LOG` | `base` | `#NUM!` (base=0) | `2` (base=10) | No — HF matches Excel |
| `VLOOKUP` | `sorted` | `#N/A` (exact match) | `"one"` (sorted) | No — HF matches Excel |
| `MATCH` | `matchType` | `#N/A` (exact) | `1` (approx) | No — HF matches Excel |
| `ADDRESS` | `absNum` | `"$A$1"` (abs=1) | `"$A$1"` (abs=1) | **Yes — HF gives `0`** |
| `ADDRESS` | `a1Style` | `"$A$1"` (a1=true) | `"$A$1"` (a1=true) | **Yes — HF gives `false`** |

### Root cause

In `FunctionPlugin.coerceArgumentsToRequiredTypes`, the guard checks only for `undefined` when selecting the `defaultValue`. `EmptyValue` passes through and is coerced to `0`/`false`.

### Fix

Add an opt-in `emptyAsDefault` flag to `FunctionArgument` metadata. When set, `EmptyValue` is treated as omitted (uses `defaultValue`). Applied only to ADDRESS `absNum` and `a1Style` parameters.

### Reproduction steps

```typescript
const hf = HyperFormula.buildFromArray([
  ['=ADDRESS(1,1,)'],   // empty absNum — should be "$A$1", bug: error or wrong format
  ['=ADDRESS(1,1,1,)'], // empty a1Style — should be "$A$1"
], { licenseKey: 'gpl-v3' })
```

### HyperFormula version

3.2.0

### Your framework

_No response_

### Your environment

Node.js

### PR DESCRIPTION
**Pull request by marcin-kordas-hoc**
## Problem

When a user writes `=ADDRESS(1,1,)` or `=ADDRESS(1,1,1,)`, the empty argument
is coerced to `0`/`false` instead of using the parameter's declared `defaultValue`.

Excel 2021 and Google Sheets treat empty args as the zero-value for the type
(`0`/`FALSE`) for **all functions except ADDRESS**, where empty `absNum` and
`a1Style` use their declared defaults (1 and `true`).

Fixes #1632

## Fix

- Add `emptyAsDefault` opt-in flag to `FunctionArgument` interface
- In `coerceArgumentsToRequiredTypes`: when `rawArg === EmptyValue` AND
  `emptyAsDefault` is set AND `defaultValue` is declared → substitute `defaultValue`
- Apply `emptyAsDefault: true` only to ADDRESS `absNum` and `a1Style` parameters

## Tests

Regression tests in `handsontable/hyperformula-tests` (branch `fix/empty-default-value`):
- ADDRESS: isolated tests for empty `absNum`, empty `a1Style`, both empty
- LOG, MATCH, VLOOKUP, HLOOKUP: confirm empty → zero-value (not defaultValue)
- `optional-parameters.spec.ts`: confirms empty args use zero-value coercion (not defaultValue) when `emptyAsDefault` is not set

---

> [!NOTE]
> **Medium Risk**
> Touches core `FunctionPlugin` argument evaluation/coercion to distinguish syntactically empty arguments, which could subtly affect coercion behavior across many functions if misapplied. Change is gated behind an opt-in `emptyAsDefault` flag and only enabled for `ADDRESS` parameters in this PR.
> 
> **Overview**
> Fixes `ADDRESS` so syntactically empty optional arguments (e.g. `=ADDRESS(2,3,,FALSE())`) use the parameter `defaultValue` instead of being coerced to the type’s zero-value.
> 
> Adds an opt-in `emptyAsDefault` flag to `FunctionArgument` and extends `FunctionPlugin`’s argument evaluation pipeline to track whether each argument was syntactically empty, allowing coercion to substitute `defaultValue` when `emptyAsDefault` is enabled. Documentation and changelog are updated to reflect the new option and the `ADDRESS` behavior fix.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 7c6fc7c8097bd45af74f645ba4e6355427c201b7. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: src/interpreter/plugin/FunctionPlugin.ts [hunk 1]
```diff
@@ -231,6 +232,14 @@ export interface FunctionArgument {
    * If set, numerical arguments need to be greater than `greaterThan`.
    */
   greaterThan?: number,
+
+  /**
+   * If set to `true`, an empty argument (EmptyValue) is treated as if the argument
+   * was omitted — i.e., replaced by `defaultValue`. This matches Excel behavior for
+   * functions like ADDRESS where empty args use declared defaults instead of the
+   * zero-value for the type.
+   */
```
Comment (sequba) [inline src/interpreter/plugin/FunctionPlugin.ts:248]: This description will go into our API documentation. It needs to be clear for someone who doesn't know the concept of `EmptyValue`. Also it must contain an example to show the difference between providing an empty argument and not providing argument at all. If think, you can add a table:

| Formula | with `emptyAsDefault=false` | with `emptyAsDefault=true` |
| - | - | - |
| `ADDRESS(2,3)` | uses `defaultValue` for 3rd argument | uses `defaultValue` for 3rd argument |
| `ADDRESS(2,3,)` | uses `0` for 3rd argument | uses `defaultValue` for 3rd argument |

**Review by sequba — CHANGES_REQUESTED** [review]
Good job, solid fix.

Please:
- add a CHANGELOG.md entry describing the fix
- update the documentation (custom-functions guide) to describe the new `emptyAsDefault` configuration param

**Review by sequba — APPROVED** [review]
